version: 2
jobs:
  test:
    docker:
      - image: cimg/python:3.9.13
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            make test_requirements

  deploy_to_dev:
    docker:
      - image: cimg/python:3.9.13
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            make test_requirements
            make publish

workflows:
  version: 2
  test_and_deploy_to_dev:
    jobs:
      - test
      - deploy_to_dev:
          requires:
            - test
          filters:
            branches:
              only: master
