# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-10 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('satisfied', models.BooleanField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('view_name', models.CharField(max_length=255)),
                ('utm_params', models.TextField(null=True)),
                ('session', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
