# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('thumber', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContentFeedback',
            new_name='Feedback',
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Feedback'},
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='utm_params',
            new_name='view_args',
        ),
    ]
